name: CI
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
    branches:
    - main
jobs:
  docs:
    name: Build demo site
    runs-on: ubuntu-latest
    environment: build-ci
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project="." -e '
            using Pkg
            Pkg.instantiate()'
      - run: julia --project="." site/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}