name: CI
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
    branches:
    - main

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: write

jobs:
  docs:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3

      - name: Restore datasets
        id: cache-datasets-restore
        uses: actions/cache/restore@v3
        with:
          path: data/
          key: ${{ matrix.os }}-dataset

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --project="." -e '
            using Pkg
            Pkg.instantiate()'
      - if: matrix.os == 'windows-latest'
        name: "Run in debug mode on windows"
        run: $env:JULIA_DEBUG="all"
      - run: julia --project="." site/make.jl
        env:
          AppID: ${{ secrets.APPID }}
          AppSecret: ${{ secrets.APPSECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      - name: Save datasets
        id: cache-datasets-save
        uses: actions/cache/save@v3
        with:
          path: data/
          key: ${{ steps.cache-datasets-restore.outputs.cache-primary-key }}